//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30311.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidpub.Admin {


    public partial class Details {

        protected global::System.Web.UI.WebControls.Content headContent;

        protected global::System.Web.UI.WebControls.Content Content1;

        protected global::System.Web.DynamicData.DynamicDataManager DynamicDataManager1;

        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;

        protected global::System.Web.DynamicData.DynamicValidator DetailsViewValidator;

        protected global::System.Web.UI.WebControls.FormView FormView1;

        protected global::System.Web.UI.WebControls.EntityDataSource DetailsDataSource;

        protected global::System.Web.UI.WebControls.QueryExtender DetailsQueryExtender;

        protected global::System.Web.DynamicData.DynamicHyperLink ListHyperLink;
    }
}
