{
"shipping_address":
    {
    "name":"Steve Shipper",
    "address1":"123 Shipping Street",
    "city":"Shippington",
    "company":"Shipping Company",
    "address2":null,
    "latitude":null,
    "zip":"K2P0S0",
    "country_code":"*",
    "country":"Shippington Emirates",
    "province_code":null,
    "last_name":"Shipper",
    "phone":"555-555-SHIP",
    "longitude":null,
    "province":"SH",
    "first_name":"Steve"
    },
"order_number":1234,
"number":234,
"name":"#9999",
"total_discounts":"0.00",
"created_at":"2011-08-17T23:40:26-04:00",
    "line_items":[
        {
            "name":"Sledgehammer",
            "price":"199.99",
            "product_id":null,
            "quantity":1,
            "requires_shipping":true,
            "title":"Sledgehammer",
            "grams":5000,
            "sku":"SKU2006-001",
            "fulfillment_status":null,
            "variant_title":null,
            "vendor":null,
            "fulfillment_service":"manual",
            "variant_id":null
        },
        {
            "name":"Wire Cutter",
            "price":"29.95",
            "product_id":null,
            "quantity":1,
            "requires_shipping":true,
            "title":"Wire Cutter",
            "grams":500,
            "sku":"SKU2006-020",
            "fulfillment_status":null,
            "variant_title":null,
            "vendor":null,
            "fulfillment_service":"manual",
            "variant_id":null
         }
      ],
    "billing_address":
    {
        "name":"Bob Biller",
        "address1":"123 Billing Street",
        "city":"Billtown",
        "company":"My Company",
        "address2":null,
        "latitude":null,
        "zip":"K2P0B0",
        "country_code":"*",
        "country":"United Bills",
        "province_code":null,
        "last_name":"Biller",
        "phone":"555-555-BILL",
        "longitude":null,
        "province":"BL",
        "first_name":"Bob"
        },
    "cancel_reason":"customer",
    "tax_lines":[],
    "note_attributes":[],
    "updated_at":null,
    "total_price":"239.94",
    "token":null,
    "taxes_included":false,
    "landing_site":null,
    "id":123456,
    "cancelled_at":"2011-08-17T23:40:26-04:00",
    "total_line_items_price":"229.94",
    "referring_site":null,
         "shipping_lines":[
            {
                "price":"10.00",
                "code":null,
                "title":"Generic Shipping"
            }
          ],
    "subtotal_price":"229.94",
    "note":null,
    "gateway":"bogus",
    "fulfillment_status":"pending",
    "financial_status":"voided",
    "currency":null,
    "closed_at":null,
    "buyer_accepts_marketing":true,
    "total_tax":"0.00",
    "landing_site_ref":null,
    "browser_ip":null,
    "total_weight":0,
    "email":"bob@biller.ca"
  }