//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30311.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidpub.Admin {


    public partial class _Default {

        protected global::System.Web.UI.WebControls.Content headContent;

        protected global::System.Web.UI.WebControls.Content Content1;

        protected global::System.Web.UI.ScriptManagerProxy ScriptManagerProxy1;

        protected global::System.Web.UI.WebControls.GridView Menu1;

        protected global::System.Web.DynamicData.DynamicHyperLink HyperLink1;
    }
}
